### ISSUE TITLE
A method for first sentence or section

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#126]
Originally reported on Google Code with ID 133

```
Would it be very nice to provide a method to fetch the first sentence or the first section
of a Page? 

Is this in the plan? Thank you.
```

Reported by `lingvisa` on 2015-06-09 08:18:29

**Comment by mawiesne** [comment]
Closing this as "won't fix" as it is not planned to provide this feature any time soon.
