### ISSUE TITLE
Snapshot dependency management

### ISSUE THREAD

**Issue by tgalery** [dkpro/dkpro-jwpl#127]
Hi, I would be quite interested in using the latest version of your lib 1.1.0-SNAPSHOT , but the version in maven central is 1.0 . Are there any instructions on how to specify your github repo as a source ?

**Comment by zesch** [comment]
This is a bit hidden on the DKPro documentation page (should be improved).
All DKPro artifacts are deployed to our Artifactory, including snapshots:
http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots/

The version you are looking for is here:
http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/repo/de/tudarmstadt/ukp/wikipedia/de.tudarmstadt.ukp.wikipedia/1.1.0-SNAPSHOT/
