### ISSUE TITLE
Switch license from LGPL to ASL

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#128]
We have been using the permissive Apache Software License in most DKPro projects, and there is no obvious reason why not to do so for JWPL (which seems to be LGPL for legacy reasons).

* [x] delete `@author` annotations in own code, a second pair of eyes over the NOTICE files and license headers, update Github pages for ASL.
* [x] NOTICE files could probably be more detailed.

**Comment by logological** [comment]
Are you sure it's for legacy reasons only?  I see a lot of third-party copyright notices in the source code:

```
$ find . -iname '*.java' -exec fgrep Copyright {} \;|sort|uniq
 * Copyright 2005 by Brion Vibber
 * Copyright 2005, JBoss Inc., and individual contributors as indicated
 * Copyright 2006 by Aurimas Fischer
 * Copyright 2006 by Brion Vibber
 * Copyright 2006 by Tim Starling
 * Copyright (C) 2005 by Brion Vibber
 * Copyright (c) 2010 Torsten Zesch.
 * Copyright (c) 2010 Torsten Zesch. All rights reserved. This program and the
 * Copyright (c) 2011 Ubiquitous Knowledge Processing Lab
 * Copyright (c) 2011 Ubiquitous Knowledge Processing (UKP) Lab
```

If the third-party code is licensed under the LGPL we can't summarily relicense it under Apache without first securing permission from the copyright holders.

**Comment by reckart** [comment]
Code that is in the package but not authored by the project members should remain under the original licenses (although depending on the license, it is possible to add another license on top of it - cf. what LibreOffice has done to OpenOffice). 

Blindly killing license headers and replacing them is clearly not the way to go. Best, such code should be isolated in specific packages and be clearly highlighted in a NOTICE file.

**Comment by daxenberger** [comment]
While scanning through JWPLs dependencies, I found one critical package: mysql-connector-java (MySQL Connector/J - mysql's JDBC) is GPLv2. This should be a problem even to JWPL's current LGPL or am I mistaken?

**Comment by reckart** [comment]
As long as we do not directly link to the driver, that should not be a problem. 
The code should still compile if the dependency is not there - does it?

If that is the case, the dependency is "just" a convenience for the user.
If the dependency is needed during testing (not for compiling tests, but for running them), it could be change to have the scope "test".

**Comment by daxenberger** [comment]
You're right. mysql-connector-java  is a runtime dependency in most modules. I'll test later, but I am pretty sure JWPL compiles without.

**Comment by daxenberger** [comment]
Ok, JWPL compiles and runs tests without mysql JDBC. Can we keep it as a runtime dependency, or should it be removed at all?

**Comment by reckart** [comment]
Having it as a runtime dependency is a convenience for users who don't have to add it themselves then. The alternative would be to document it and not have the dependency.

Do we create a far jar or other kind of distribution packaging for JWPL?

**Comment by daxenberger** [comment]
Fat jars were available on Google Code, but since we switched to github, they are only available via maven central. I guess we should remove the dependency then.

**Comment by judithek** [comment]
what about the FOSS exception?
http://www.mysql.com/about/legal/licensing/foss-exception/

doesn't it apply here as well?

**Comment by reckart** [comment]
That should apply for JWPL too. But since we don't directly link to the driver, I am not sure if we even need to resort to the FOSS exception.

**Comment by daxenberger** [comment]
Right, thanks Judith. No need to change any dependencies.

**Comment by daxenberger** [comment]
The de.tudarmstadt.ukp.wikipedia.mwdumper and de.tudarmstadt.ukp.wikipedia.wikimachine modules contain 3rd party code, and need updates to their NOTICE files.

**Comment by daxenberger** [comment]
Updated NOTICE files in 356cd0497a9a9f6a8635d6e96b6f5345fd9f5293.

**Comment by daxenberger** [comment]
TODOs: delete @author annotations in own code, a second pair of eyes over the NOTICE files and license headers, update Github pages for ASL.
NOTICE files could probably be more detailed.

**Comment by daxenberger** [comment]
Done.
Please somebody verify the changes and close the issue.

**Comment by zesch** [comment]
Verified.

**Comment by logological** [comment]
Reopening this issue for the following reasons:

* There is conflicting licence information in `de.tudarmstadt.ukp.wikipedia.revisionmachine`.  The `pom.xml` file claims that the module (presumably all of it) is licensed under the GNU LGPLv3, but the `LICENSE.txt` file is for the Apache License 2.0.  Which is it?  I suspect the entire module is UKP-authored, in which case we just need to remove the references to the LGPL from the POM.

* The `de.tudarmstadt.ukp.wikipedia.wikimachine` and `de.tudarmstadt.ukp.wikipedia.api` modules claim to be Apache-licensed in their respective `LICENSE.txt` files, but individual source files still bear GNU LGPLv3 or GNU LGPL v2.1 copyright notices.  The LGPLv3 notices are from @zesch ; if he is the only author then he can relicense these under Apache.  However, the GNU LGPL v2.1-licensed file, `HashStringUtil.java`, looks like it's from a third party.  It can't be summarily relicensed by us, and we're currently in violation of its license by not distributing the text of the GNU LGPL v2.1.  (If we are distributing binaries, then we may also be in violation of the Apache License – at least, [Apache seems to think that the ASL and LGPL are incompatible](https://www.apache.org/legal/resolved.html#category-x).)

**Comment by reckart** [comment]
@logological ASF & LGPL : Apache has a policy that licenses used in ASF produces should not impose any restrictions/obligations to downstream users that go beyond what the Apache License imposes. This is why the LGPL is under Category X for ASF products. We do not need to follow that policy. If we continue to include the file in JWPL if we must retain the original license header, we should mention the file origin in the NOTICE.txt file and we should add the LGPL to the LICENSE.txt file with a pointer to the respective file. The code is not terribly complex it seems. If we really need that, maybe we can just reimplement it?

**Comment by logological** [comment]
Regarding `HashStringUtil.java`, you're right that it's pretty simple.  I will reimplement it.

**Comment by logological** [comment]
The LGPL code in `HashStringUtil` consisted of a class with a single, public static method.  This method was used by only one other class `StringHashCodeJBoss`, so I moved the code there and deleted `HashStringUtil`.   It's possible that third-party code using DKPro JWPL directly calls the now-deleted static method, though I think this is exceedingly unlikely.  If anyone disagrees, I'll restore the class and static method, mark it as deprecated, and then remove it after the next release.

**Comment by logological** [comment]
@zesch Do you have any objection to my changing the licence in your LGPL files in `de.tudarmstadt.ukp.wikipedia.revisionmachine` to the Apache Software License 2.0?

**Comment by zesch** [comment]
No objections. I think it was decided some time ago to make the switch anyway.

**Comment by logological** [comment]
OK.  I'm assuming, then, that any code currently credited to authors listed in `CONTRIBUTORS.txt` is supposed to be Apache-licensed, and will now change it as such.  After this, as far as I know, there will be no files in DKPro JWPL marked as being licensed under the LGPL.

**Comment by zesch** [comment]
yes, please proceed. Thanks.
