### ISSUE TITLE
Is de.tudarmstadt.ukp.wikipedia.dist module still needed?

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#130]
Is this module still up-to-date and do we still need it?

**Comment by zesch** [comment]
I am not really sure what this module was used for.

**Comment by daxenberger** [comment]
Anybody? Otherwise, we might just get rid of it.

**Comment by reckart** [comment]
I'd say it way used to build a kind of fat JAR via a Maven assembly. @ferschke did that if I remember right. For me, I'm +1 on removing it.

**Comment by ferschke** [comment]
Yes, that was used to create runnable fatjars. If those are no longer used,
this can be removed.

-Oliver

**Comment by daxenberger** [comment]
We distribute jars-with-dependencies via Maven Central. Does the dist module have any advantage over this?

**Comment by reckart** [comment]
Is the dist module the way this " jars-with-dependencies" is created? Who is this jars-with-deps for anyway?

**Comment by daxenberger** [comment]
Good question. @ferschke I think you performed the last release. Are the jars-with-dependencies on Maven Central created with the dist module?

**Comment by reckart** [comment]
Apparently not: https://github.com/dkpro/dkpro-jwpl/search?utf8=✓&q=jar-with-dependencies

Looks like each module creates it's own.

**Comment by ferschke** [comment]
That was really just for the fatjars that we used to manually upload to google code. No reason to keep this module.

**Comment by daxenberger** [comment]
Now it's gone.
