### ISSUE TITLE
Is Timemachine able to generate an xml dump resembling pages-articles.xml

### ISSUE THREAD

**Issue by dav009** [dkpro/dkpro-jwpl#131]
Documentation says Timemachine is able to generate a JWPL databases, I wonder if it is possible to get a xml dump resembling the one offered by wikipedia (pages-articles.xml).

If not would it imply a lot of refactor changes on jwpl to make it get one out?

Thanks

**Comment by daxenberger** [comment]
I don't think JWPL is the right tool for that. The time machine creates a JWPL database resembling a previous Wikipedia state, but not old dump (xml) files. 
However, many older dump files can be found on archives such as the ones listed here: https://dumps.wikimedia.org/archive
