### ISSUE TITLE
Clean up file structure

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-jwpl#135]
Many modules contain non-Java files in the `src/main/java` hierarchy, and miscellaneous XML and settings files in the root directory or in other odd places.  These should be moved to more appropriate locations (`src/main/resources`, `src/test/resources`, etc.) and references to them should be updated.

Here is a (probably complete) list:

```
de.tudarmstadt.ukp.wikipedia.datamachine/decompressor.xml
de.tudarmstadt.ukp.wikipedia.timemachine/config_file_arabic_one_snapshot.xml
de.tudarmstadt.ukp.wikipedia.timemachine/config_file_greek_one_snapshot.xml
de.tudarmstadt.ukp.wikipedia.timemachine/decompressor.xml
de.tudarmstadt.ukp.wikipedia.parser/src/main/java/de/tudarmstadt/ukp/wikipedia/parser/html/ParsedPage.css
de.tudarmstadt.ukp.wikipedia.parser/src/main/java/de/tudarmstadt/ukp/wikipedia/parser/tutorial/DarmstadtWikipediaArticle.txt
de.tudarmstadt.ukp.wikipedia.wikimachine/src/main/java/context/applicationContextTemplate.xml
de.tudarmstadt.ukp.wikipedia.revisionmachine/src/main/examples/configSamples/indexGenerator_config_sample
de.tudarmstadt.ukp.wikipedia.revisionmachine/src/main/examples/configSamples/diffTool_config_sample.xml
```

**Comment by logological** [comment]
As far as I can tell, the following files are not read by any executable code in DKPro JWPL:

```
de.tudarmstadt.ukp.wikipedia.timemachine/config_file_arabic_one_snapshot.xml
de.tudarmstadt.ukp.wikipedia.timemachine/config_file_greek_one_snapshot.xml
de.tudarmstadt.ukp.wikipedia.parser/src/main/java/de/tudarmstadt/ukp/wikipedia/parser/html/ParsedPage.css
de.tudarmstadt.ukp.wikipedia.parser/src/main/java/de/tudarmstadt/ukp/wikipedia/parser/tutorial/DarmstadtWikipediaArticle.txt
de.tudarmstadt.ukp.wikipedia.wikimachine/src/main/java/context/applicationContextTemplate.xml
```

Can anyone tell me how they are being used, if at all?

If they are not being used at all, they should be deleted.  If they are being used (as example files, perhaps), then they should be moved somewhere more appropriate (into the online documentation, into `src/main/resources/examples`, etc.).

**Comment by zesch** [comment]
The config files are example files for other languages. I think they are in the right location right now, even if they are currently not used.

The .css file is used to nicely render the ParsedPage object in HTML. Probably the .txt file was used as an example at some point, but could be moved to 'resources'.

The last one is a template file that gives an example for the other .xml files that are actually used. I also think that it is in the right place right now.

**Comment by mawiesne** [comment]
Closing this as "completed" as the cleanup has been done in the past. This issue wasn't closed however, or nobody remembered it existed.
