### ISSUE TITLE
UniversalDecompressor hard-codes configuration file location

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-jwpl#136]
In the `UniversalDecompressor` class of the wikimachine module, the path to the decompressor XML configuration file is hard-coded.  This makes it impossible for users (other than those compiling from source) to specify a decompressor of their choice.  The class should be rewritten to take a user-specified file location.

**Comment by mawiesne** [comment]
@logological Any specific requirements from your side?

**Comment by logological** [comment]
No. Just change the class to take a user-specific file location.
