### ISSUE TITLE
DataMachine FEATURE_SECURE_PROCESSING

### ISSUE THREAD

**Issue by nitishgupta** [dkpro/dkpro-jwpl#139]
When trying to run DataMachine using command line to make the .txt files, error comes.
' org.xml.sax.SAXParseException; lineNumber: 67704664; columnNumber: 218; JAXP00010004: The accumulated size of entities is "50,000,001" that exceeded the "50,000,000" limit set by "FEATURE_SECURE_PROCESSING". '

Have tried command line arguments DtotalEntitySizeLimit=500000000 -DentityExpansionLimit=500000000 but still doesn't work.

**Comment by daxenberger** [comment]
Could you paste your solution into the issue as well (for documentation)? Thanks!

**Comment by nitishgupta** [comment]
`System.setProperty("jdk.xml.totalEntitySizeLimit", "500000000");
                SAXParserFactory spf = SAXParserFactory.newInstance();
                spf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, false);
                // Path where wiki dump is stored.
                String[] arg = {"english", "Contents", "Disambiguation_pages", "PATH/TO/WIKIDUMP/"};
                JWPLDataMachine.main(arg);`

**Comment by daxenberger** [comment]
Thanks!
