### ISSUE TITLE
java framework that allows me to get all Wikipedia articles, with geographic location

### ISSUE THREAD

**Issue by mpuebla** [dkpro/dkpro-jwpl#142]
I am interested in knowing if there is a java framework that allows me to get all Wikipedia articles, with geographic location located in a zone (boundingBox). Something like: all the articles located in Cuba.

Is there any tool that gives me this type of information?

Greetings.

**Comment by daxenberger** [comment]
I'm not sure if I understand correctly. If you want to retrieve all Wikipedia articles in a certain language, that mention a specific geographic location somewhere in the article text (e.g. in an infobox), you can do this with JWPL theoretically, but it will require to write your won "parser"/regex that searches for such information. It is not indexed by JWPL so that you could directly search for it.

**Comment by mpuebla** [comment]
No, no ... I'm not interested in the language in which the article is written, nor am I interested in the coordinates to which they refer in the text of the article. What interests me are the more than 4.5 million georeferenced articles that are now on Wikipedia, every day that goes on increasing the georeferenced articles, thanks to this project: https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Geographical_coordinates .

That is, there is a growing movement today in Wikipedia, to georeferencing the articles. I investigate Geographic Information Retrieval, and I wonder if "jwpl" is already able to get the geographical location of the georeferenced items. Maybe he has not included it yet, but I do not think it's a complicated job, because geo-referenced articles have geographic coordinates in their workforce. There is no need to make a parser, just get the coordinates of the template.

I hope I have explained adequately, my apologies for the errors in the language.

Best Regards, Manuel Puebla.

**Comment by daxenberger** [comment]
Ok I guess I understand what you want.
My answer basically remains the same as above: yes, you can use JWPL to get this information, but you need to invest some extra effort to extract a) the templates themselves from the articles you want, and b) the coordinates within the templates. JWPL recommends the sweble parser for this kind of thing - it is able to work with templates. One usage example can be found in `de.tudarmstadt.ukp.wikipedia.api`: `de.tudarmstadt.ukp.wikipedia.api.sweble.TemplateNameExtractor`

**Comment by mawiesne** [comment]
I close this issue, as this is no bug report and no actual feature request or proposed enhancement, yet a request for guidance. @daxenberger if your opinion differs, feel free to reopen this issue.

**Comment by daxenberger** [comment]
Fine with me.
