### ISSUE TITLE
Datamachine exception

### ISSUE THREAD

**Issue by shatu** [dkpro/dkpro-jwpl#144]
While trying to use the Datamachine on one of the recent versions of Wikipedia (1st March 2017), I get the following error :-

> "2017.03.13 17:20:53","1552941056","1398379112","org.xml.sax.SAXParseException; lineNumber: 64370855; columnNumber: 559; JAXP00010004: The accumulated size of entities is "50,000,001" that exceeded the "50,000,000" limit set by "FEATURE_SECURE_PROCESSING".
> 
> de.tudarmstadt.ukp.wikipedia.wikimachine.dump.xml.AbstractXmlDumpReader.readDump(AbstractXmlDumpReader.java:209)
> de.tudarmstadt.ukp.wikipedia.datamachine.dump.xml.XML2Binary.<init>(XML2Binary.java:47)
> de.tudarmstadt.ukp.wikipedia.datamachine.domain.DataMachineGenerator.processInputDump(DataMachineGenerator.java:70)
> de.tudarmstadt.ukp.wikipedia.datamachine.domain.DataMachineGenerator.start(DataMachineGenerator.java:64)
> de.tudarmstadt.ukp.wikipedia.datamachine.domain.JWPLDataMachine.main(JWPLDataMachine.java:64)"

**Comment by kunalsheth** [comment]
https://github.com/dkpro/dkpro-jwpl/issues/139

**Comment by shatu** [comment]
Thanks! Will try out the proposed solution and will close the issue.

**Comment by shatu** [comment]
For the record, that's how the original author of the issue addressed this problem :- https://groups.google.com/forum/#!msg/jwpl/EhuqKpF2jag/jJO153TdBAAJ

**Comment by kunalsheth** [comment]
I am not sure why that has not been done already, I will look into it

**Comment by shatu** [comment]
The solution suggested in #139 works; refer to https://groups.google.com/forum/#!msg/jwpl/EhuqKpF2jag/jJO153TdBAAJ if unclear.
