### ISSUE TITLE
Documentation of Filters used in DataMachine?

### ISSUE THREAD

**Issue by shatu** [dkpro/dkpro-jwpl#146]
Is there some easily available documentation of the filters that you use inside DataMachine? Basically, what i'm interested in figuring out is things like :-

1. Do you have any filter on the minimum article/document length somewhere?
2. Do you remove the hidden categories from the system?
3. Do you expand the templates?
4. Do you filter out pages from namespaces other than 0 ("articles") and 14 ("categories")?
5. When queried for the categories of a page, do you recursively follow the path to the root and return the parents of directly mentioned categories as well, or just return the directly mentioned categories? For instance, an editor might have just put "Political System" as Category for a particular page, but "Political System" category might itself be a child of "Politics". So, will your system return just "Political System" here, or "Politics" as well?

If possible, please also tell me which files in the source code helped you figure out answers to these.

P.S. Posting it as an issue on Github since the corresponding Google Group seems to be inactive.

**Comment by daxenberger** [comment]
The mailing ist is not inactive, just a bit slow...
Closing this issue; see comments on mailing list.
