### ISSUE TITLE
get HTML sourcecode

### ISSUE THREAD

**Issue by rwelte** [dkpro/dkpro-jwpl#148]
Hi,

how can I get the html sourcecode of an entire Wiki page?

Thanks in advance!

**Comment by zesch** [comment]
You can only get the MediaWiki markup version via Page.getText()
How this is finally rendered as HTML is the job of MediaWiki and beyond the scope of this API.

**Comment by rwelte** [comment]
Thanks! Is there a way to parse only a part of markup code to "plain text" with jwpl? If so, could you please give me an example?

**Comment by zesch** [comment]
It is not directly supported, but you can have a look at Page.getPlainText() and adapt it to your needs.
