### ISSUE TITLE
[DataMachine] No appenders could be found for logger .  Please initialize the log4j system properly.

### ISSUE THREAD

**Issue by MeriTxellSaVe** [dkpro/dkpro-jwpl#153]
Hi,
I've opened the project with Eclipse and changed JWPLDataMachine path as it's requested, but I get this warning message:

log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.

How can I fix it?

Thanks

**Comment by reckart** [comment]
One way is placing a log4j.properties file into your classpath.

A simple log4j.properties file could look like this:

```
log4j.rootLogger=WARN,development

log4j.appender.development=org.apache.log4j.ConsoleAppender
log4j.appender.development.layout=org.apache.log4j.PatternLayout
log4j.appender.development.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %5p [%t] (%C{1}) - %m%n
```


For more info, see https://logging.apache.org/log4j/1.2/manual.html
