### ISSUE TITLE
The entity number exceed

### ISSUE THREAD

**Issue by keepRunning2017** [dkpro/dkpro-jwpl#154]
When I used de.tudarmstadt.ukp.wikipedia.datamachine-1.0.0-jar-with-dependencies to parse chinese wiki dumps, it reported that the entity number exceeded 50000000. Could anyone solve this problem?

**Comment by daxenberger** [comment]
Which "entity number"? Can you post the entire error message or give more details?

**Comment by zesch** [comment]
This is a known issue - see here:
https://github.com/dkpro/dkpro-jwpl/issues/144
