### ISSUE TITLE
Introduce checkstyle

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-jwpl#164]
We have a Maven-based checkstyle configuration compatible with the [DKPro style profiles](https://dkpro.github.io/contributing/) in DKPro Core. This could be transferred to JWPL.

**Comment by mawiesne** [comment]
Should this be part of milestone [1.2.0](https://github.com/dkpro/dkpro-jwpl/milestone/2) or shall we put it into [1.2.1](https://github.com/dkpro/dkpro-jwpl/milestone/3)? 

Feel free to assign it.
