### ISSUE TITLE
Query did not return a unique result for "existsPage(String title)" after introduction of HSQL-DB tests

### ISSUE THREAD

**Issue by mawiesne** [dkpro/dkpro-jwpl#174]
With the lastest changes introduced with #2, we encounter a regression and observe this stacktrace when working against a MySQL production backend:

```
org.hibernate.NonUniqueResultException: query did not return a unique result: 3
	at org.hibernate.query.internal.AbstractProducedQuery.uniqueElement(AbstractProducedQuery.java:1487)
	at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1457)
	at de.tudarmstadt.ukp.wikipedia.api.Wikipedia.existsPage(Wikipedia.java:633)
	at de.hshn.mi.tulum.graph.wikigraph.service.domain.impl.JWPLWikipediaSourceImpl.existsPage(JWPLWikipediaSourceImpl.java:45)
```

The reason for this that I removed `... COLLATE utf8_bin` in #2 (as this is unsupported with HSQL-DB) from the native SQL query in this method. 

The fix is simple: 
Add this MySQL specific text fragment in case `Wikipedia` uses a MySQL-driven `DatabaseConfiguration`.

I will provide a fix for it (and potentially similar cases).

**Comment by reckart** [comment]
Is this something that should be handled in queries or rather in the database setup itself (i.e. setting the database-wide default collation during database creation)?

**Comment by mawiesne** [comment]
@reckart I'm only restoring existing code/functionality with this issue. For the HSQL-DB embedded scenario "collation" is not supported at all. Thus, we can not set a "default" collation any way.

**Comment by reckart** [comment]
The code handled the collation before, but I wonder if it is worth to introduce DB-specific code for something that could as well be documented and handled when the user manually creates the MySQL DB - the user has to do that anyway and could probably easily set the the default charset and collation for the DB at that point. It could maybe also be done at the time when JWPL is setting up the database schema - but I *think* it should not be necessary to handle this at query time.

**Comment by rzo1** [comment]
Well, this could be an **improvement**. However, the current **master** is **broken** and lead to unexpected behaviour in projects depending on JWPL snapshots for integration / testing purposes.

I agree, that **utf8_bin collation** in queries should be removed from the query level and the code-base but we should first fix the **master** branch to reduce pain for other devs / projects.

I propose the following strategy:

- (a) Fix the **master** branch by introducing a strategy to distinguish between HSQLDB and MYSQL at query level.

- (b) Next (other issue), remove **utf8_bin collation** in queries and provide documentation on how to setup MYSQL with correct collation for using it with JWPL.

**Comment by reckart** [comment]
@rzo1 fine by me 👍
