### ISSUE TITLE
Modernize JWPL maven plugins and related tooling via update to dkpro-parent-pom version 19

### ISSUE THREAD

**Issue by mawiesne** [dkpro/dkpro-jwpl#176]
At the moment, JWPL refers to version **15** of _dkpro-parent-pom_. With the more recent version **19**, the project will benefit by several plugin updates which allow Java9+ build environments.

### Tasks

- [x] Update to version 19
- [x] Check build passes locally
- [ ] Check Jenkins CI server to work properly.

See: http://search.maven.org/#artifactdetails|org.dkpro|dkpro-parent-pom|19|jar

**Comment by reckart** [comment]
@mawiesne I think if you just update the parent pom version in the top-level JWPL POM, things should "simply work".

**Comment by mawiesne** [comment]
Will try, push a branch, open a PR to check with Jenkins.

**Comment by mawiesne** [comment]
fixed via PR #176
