### ISSUE TITLE
Provide method to retrieve a page's categories by page title 

### ISSUE THREAD

**Issue by VanChriz** [dkpro/dkpro-jwpl#178]
I need to retrieve categories for Wikipedia pages to ensure their affiliation with certain domains. Currently, that means first fetching the article, then using that to fetch categories, in multiple queries, which slows down the process. As an example, where wikiSource refers to a `Wikipedia` instance:
 
![image](https://user-images.githubusercontent.com/22494234/42751095-e4ffa532-88e9-11e8-93bb-55e5ade08be4.png)

A method that allows for categories to be fetched directly in 1 single query by providing a page title as parameter, instead of going the extra mile fetching the page first in a separate query, would constitute a performance enhancement.

**Comment by mawiesne** [comment]
@VanChriz I will work on this enhancement.

**Comment by mawiesne** [comment]
Fixed with recent merge of PR #179.
