### ISSUE TITLE
Switch to SLF4J

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-jwpl#189]
SLF4J is the standard nowadays and broadly used. It may be a good time to adopt it here as well.

**Comment by mawiesne** [comment]
I fully agree to use SL4J.

**Comment by rzo1** [comment]
+1

**Comment by mawiesne** [comment]
FYI @reckart: I will now work on this.

**Comment by mawiesne** [comment]
@reckart How shall we deal with `de.tudarmstadt.ukp.wikipedia.wikimachine.debug.ILogger` and uses of it?

**Comment by reckart** [comment]
I'm not familiar with this interface. Maybe drop it?
