### ISSUE TITLE
Use embedded DB for test cases

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#2]
Originally reported on Google Code with ID 2

```
Currently the JWPL test cases require access to our DB host. This precludes
external users from running the tests (when JWPL is open sourced) and it also
prevents tests when the DB host is offline (as currently...).

Instead an embedded DB like HSQLDB or Derby should be used for test cases.


```

Reported by `torsten.zesch` on 2010-09-21 16:07:20

**Comment by zesch** [comment]
Waking up an 8-year old issue :)
Unfortunately, I won't have time to look into it anytime soon.

**Comment by rzo1** [comment]
Any change to upload exports of the test-databases anywhere?

**Comment by reckart** [comment]
I have attached the "wikiapi_test" dump here. The others are probably way larger and rather live DBs than test DBs. But the "wikiapi_test" is used by most tests as far as I could see.

[wikiap_test.sql.gz](https://github.com/dkpro/dkpro-jwpl/files/2012166/wikiap_test.sql.gz)

**Comment by daxenberger** [comment]
After a quick check, I think we can live without "wikiapi_uk", "wikiapi_en" and "wikiapi_de" (and the respective tests/functions using them). Thus, "wikiapi_test" should either be embedded or hosted somewhere else online.

**Comment by tgalery** [comment]
Would this https://github.com/zapodot/embedded-db-junit be of any help ?

**Comment by rzo1** [comment]
What is with `wikiapi_simple_20090119` - can we replace this with `wikiapi_test`?

**Comment by mawiesne** [comment]
FYI: 
I just merged all recent changes of the **_master_** branch into my rather old **_hsqldb-tests_** branch and adapted the test scenario in there. This should be a starting point to port things to embedded, self-contained test execution. 

Next steps include to make the db schema compatible and afterwards the data contained in the dump by @reckart  above.

**Comment by reckart** [comment]
`wikiapi_simple_20090119` seems to be a dump of the `simple_english` Wikipedia from 2009-01-19.

```
id	language	disambiguationCategory	mainCategory	nrofPages	nrofRedirects	nrofDisambiguationPages	nrofCategories	version
2	simple_english	Disambiguation	Categories	70906	13703	1432	10884	NULL
```

**Comment by mawiesne** [comment]
@reckart Another thing to discuss (i) `RevisionApiTest` and (ii) `RevisionIteratorTest` in the _revisionmachine_ module. As far as I can see, both test cases rely on `wikiapi_simple_20090119` DB. 

Does anyone of you have a dump file of exactly this DB snapshot which I could convert to a HSQLDB script file? If not, is there any other dump which is available?  

Last option: Make two integration tests out of it and let it run against a UKP/HHN dependent local MySQL setup which can be switched/activated via separate maven profiles.

What is your opinion on this?

**Comment by daxenberger** [comment]
> Does anyone of you have a dump file of exactly this DB snapshot which I could convert to a HSQLDB script file? If not, is there any other dump which is available?

@mawiesne I've made a copy of this sql dump available [here](https://fileserver.ukp.informatik.tu-darmstadt.de/jwpl/wikiapi_simple_20090119.sql). Will you be able to work with that?

**Comment by mawiesne** [comment]
@daxenberger thx for providing this dump  👍, downloaded it already. I will strip the sql dump to the essential part that is needed for the tests to work correctly. I think embedding a stripped version of it in `src/test/java` (module: revisionmachine) might be a first starting point to. I've already reworked the test to work fine with HSQL environments. Now I can "glue" in the test data.

**Comment by daxenberger** [comment]
Perfect. The dump is quite large; but let's see what can be stripped away ...

**Comment by mawiesne** [comment]
@daxenberger While changing the test environment to HSQLDB I just found a 🐛 in `RevisionIterator.query()` and fixed it en passant. 

For documentation of it, I leave it here as a comment:
```
statement=this.connection.prepareStatement(query);
result = statement.executeQuery(query)
```

Runs into a similar issue as this one here: 
https://stackoverflow.com/questions/3762533/hsqldb-cryptic-exception-message-feature-not-supported

It should read, else a it violates the JDBC contract:

```
statement=this.connection.prepareStatement(query);
result = statement.executeQuery()
```

Will be fixed with next commit.
