### ISSUE TITLE
Running the revision machine

### ISSUE THREAD

**Issue by syedarehaq** [dkpro/dkpro-jwpl#208]
I tried to run the revision machine tool but failed with different wayforwards.

First I tried to follow the instruction here:
https://dkpro.github.io/dkpro-jwpl/RevisionMachine/

To get the revision machine jar, I have downloaded the fatjars for version 1.0.0 by using the following link:
https://search.maven.org/artifact/de.tudarmstadt.ukp.wikipedia/de.tudarmstadt.ukp.wikipedia.revisionmachine/1.0.0/jar

Then I tried to use:

```
java -jar de.tudarmstadt.ukp.wikipedia.revisionmachine-1.0.0-jar-with-dependencies.jar 
```

Which gives me the following error:
```
no main manifest attribute, in de.tudarmstadt.ukp.wikipedia.revisionmachine-1.0.0-jar-with-dependencies.jar
```

Now if I wanted to follow the actual instruction I needed to run `de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.config.gui.ConfigGUI` and `de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.DiffT`. 

But I do not understand from where to run them.

Please pardon my java ignorance, I really appreciate your help here on running the revisionmachine.

**Comment by reckart** [comment]
I think you need to put the class name behind the JAR and use `-cp` instead of `-jar`

```
$ java -cp de.tudarmstadt.ukp.wikipedia.revisionmachine-1.0.0-jar-with-dependencies.jar de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.config.gui.ConfigGUI
```

@zesch

**Comment by syedarehaq** [comment]
Perfect! The swing app is now running! Thanks for the help!
