### ISSUE TITLE
Release JWPL 2.0.0

### ISSUE THREAD

**Issue by mawiesne** [dkpro/dkpro-jwpl#230]
- [x] Resolve all open issues for 2.0.0 (https://github.com/dkpro/dkpro-jwpl/milestone/14)
- [x] Check dependencies
- [x] Run release
- [x] Publish artifacts to Maven Central
- [x] Update website

**Comment by reckart** [comment]
Normally, the artifacts are published as part of the release - at least if I run the release locally.
