### ISSUE TITLE
Automatically Close Stale Issues and PRs

### ISSUE THREAD

**Issue by rzo1** [dkpro/dkpro-jwpl#238]
Introduce https://github.com/actions/stale to automatically close issues after 90 days of inactivity. 

Most of the current issues are too old, so if we release 2.0.0 they might need to be reproduced anyway or are invalid as they target 0.9.1

**Comment by reckart** [comment]
Is it possible to configure that thing more smartly than just closing an issue after a time? For example, it should only apply to bugs, not to features or questions. Also, it should probably not close issues if the release the report applies to is still relatively recent in teams of releases (e.g. a bug report against 2.1.x should maybe only be closed once 2.6.x or higher is released).

**Comment by rzo1** [comment]
My reasoning behind this is the following:

If a bug is open for a long time and there is no interest to fix it (either by a PR of the user or by a maintainer) then it might never get fixed, i.e. from my point of view it is ok to mark the issue as "stale" after 90 or 180 days and close it 7 days later if necessary. People can still find it in the issue tracker and re-open, if needed.

The 7 days are also configurable via https://github.com/actions/stale#days-before-close. In this time someone (issue opener or maintainer) would have the possibility to comment and keep the issue "open", if the bug is still relevant / important for the end user at all.

It is possible to configure to only look at issues which contain a pre-defined set of labels https://github.com/actions/stale#only-labels

**Comment by reckart** [comment]
I personally don't like stale issue closers - sometimes I only get to working on an issue after a couple of years. But that's only my 10ct here. I'm not actively maintaining JWPL, so if you feel you need to add that and nobody else speaks up against it, go ahead. 

-0 from me.

**Comment by rzo1** [comment]
I am going to close that as won't fix for now. @reckart convinced me ;-)
