### ISSUE TITLE
[DataMachine] Automatically delete *.bin files after dump creation process

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#24]
Originally reported on Google Code with ID 26

```
The files page.bin, revision.bin and text.bin, which are generated during the dump creaton
process, should be automatically deleted when processing has finished. They are no
longer needed.



```

Reported by `oliver.ferschke` on 2011-06-08 12:32:03

**Comment by mawiesne** [comment]
@daxenberger Has this issue ever been resolved? What is the current state for this feature request?

**Comment by daxenberger** [comment]
@mawiesne see my comments in #173

**Comment by daxenberger** [comment]
> @daxenberger I agree: .bin files are not of much interest to most (>90%) users. Please specify an optional parameter in the original issue (#24) as a comment. I could then rework the PR to reflect this idea, so users can decide whether to keep the files or not.

How about sth like a boolean DO_NOT_DELETE_TEMP_FILES in JWPLDataMachine, set to false by default?

**Comment by rzo1** [comment]
What about the command-line parameter "--keep-bin-files <true/false>" ?

**Comment by mawiesne** [comment]
@reckart Any additions? Otherwise, I'll proceed with these changes as suggested above.

**Comment by reckart** [comment]
I don't know how this code is used, but usually having static flags somewhere like a `DO_NOT_DELETE_TEMP_FILES` is not a good idea. I'd still recommend allowing local control over this behavior. But that's just my 10 cents.

**Comment by mawiesne** [comment]
I will quickly summarize our options here:

1. _Hard removal_ strategy as originally requested "on Google Code with ID 26", current state of PR #173.
2. _Soft removal_ strategy, unless `-keep-bin-files` is specified, proposed by @daxenberger / @rzo1 .
3. _Local control strategy with removal option_, i.e. keep all `.bin` files by default unless 
`-wipe-bin-files` is specified, proposed by @reckart. 
4. _Do not change code_ strategy and close this issue / remove the PR all together.

Gentlemen, please cast your vote (+1, 0, -1) for one of the aforementioned strategies. -1 in case you want to veto providing an explanation on the "why". 

I will vote, once you have commented and implement the strategy which receives a majority of the votes.

**Comment by tgalery** [comment]
Hi guys , I'd love to, but I'm on holidays at the moment. Should be able to
catch up and see how I can contribute. Hope that's ok !

**Comment by reckart** [comment]
I have given my advice, but for me it's really up to you how you prefer it. So I'm +0 for all options :)

**Comment by daxenberger** [comment]
Both option 2 and 3 are fine with me, with a slight preference for 2.

**Comment by reckart** [comment]
> Local control strategy with removal option, i.e. keep all .bin files by default unless
-wipe-bin-files is specified, proposed by @reckart.

Mind my comment was about the API of the dumper at the Java level, not at the command-line level. I believe it should be possible (if desired) to call a "cleanup" method from the code that handles the command-line invocation (e.g. some `main` method). I didn't comment on how that could be exposed to the CLI user (i.e. whether to use a delete-by-default or a keep-by-default strategy). IMHO the CLI-level design and Java API level design can very well make different decisions on this matter. That's just for clarification. I'm still +0 for everything ;)

**Comment by rzo1** [comment]
I vote for a combined approach of (2) and (3).

Implementing "cleanUp()" on API level and then using `---keep-bin-files` to prevent cleanup in CLI usage.

**Comment by mawiesne** [comment]
Decided it is, as nobody objected the proposal by @rzo1. I will implement a soft-removal strategy (Option 2) then, providing `cleanUp` method on API level.
