### ISSUE TITLE
Declare unused methods as deprecated

### ISSUE THREAD

**Issue by mawiesne** [dkpro/dkpro-jwpl#254]
Some methods are entirely unused and/or commented as deprecated. We should mark this more clearly via `@Deprecated`.

**Comment by reckart** [comment]
Deprecated methods should only be removed at major versions. It is a good practice to leave deprecated methods in a while after deprecation. However, considering that JWPL is just about to make a major version jump, it could be considered to not deprecate but remove the methods outright. Depending on the method though, you might think that it may still be useful and so should stay.

In any case, please consider using the new properties of the `@Deprecated` annotation and document what the intended upgrade path is - or if there is none - using the JavaDoc `@deprecated` tag.

```
/**
 * @deprecated Use {@link XXX#foo} instead. / or / To be removed without replacement.
 */
@Deprecated(since="2.0.0), forRemoval="3.0.0")
```

**Comment by mawiesne** [comment]
That's what I planned :)

**Comment by mawiesne** [comment]
Note: 
`@Deprecated(since="2.0.0", forRemoval=true)` is working, the other example is not consistent with what the annotation allows for.

**Comment by reckart** [comment]
Yes, indeed. In other projects in I am using a custom `@forRemoval` JavaDoc tag to mark the version for the method to be removed. That confused me here. Thanks for correcting me. If you find it helpful to announce in which version the deprecated method is expected/planned to be removed, you could also use a custom JavaDoc tag. It only requires configuring the JavaDoc Maven Plugin to make it know it is there and not warn about it.

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <notimestamp>true</notimestamp>
          <doclint>all,-missing</doclint>
          <tags>
            <tag>
              <name>forRemoval</name>
              <placement>X</placement>
            </tag>
          </tags>
        </configuration>
      </plugin>
```

Example above also includes two additional config parameters which might be useful.
