### ISSUE TITLE
Fix missing license.txt files

### ISSUE THREAD

**Issue by rzo1** [dkpro/dkpro-jwpl#255]
The `check-license.txt` profile is failing due to `LICENCE` vs `LICENSE` ambiquity. In some modules the LICENSE is missing at all.

**Comment by reckart** [comment]
Any idea why we don't use the maven-rat-plugin exclusively?

**Comment by rzo1** [comment]
No idea. The profile `check-license.txt` is inherited from the dkpro-parent (and was failing - I assumed it might be active during a release procedere, so I wanted to fix it)

**Comment by reckart** [comment]
ok, I'll have a look where this comes from. in other projects, we needed to mix rat and the license checker plugin because of a mix of GPL and ASL code (in DKPro Core) - but this should I think not apply to JWPL.

**Comment by rzo1** [comment]
There are some classes in JWPL, which are not ASLv2 and have a rather individual license (for example: `ListFilter`)

**Comment by reckart** [comment]
If they are [ASL-compatible](https://www.apache.org/legal/resolved.html), they should either be recognized by rat or can be excluded from the check and manually recorded in LICENSE / NOTICE files. If they are not compatible, they should probably be removed/replaced.

**Comment by rzo1** [comment]
They are already properly recorded in the related files and should be compatible (are around for ages now).

**Comment by reckart** [comment]
Probably, but me-from-ages-ago might also have missed them while vetting...

**Comment by rzo1** [comment]
The rat checks are active by default, so other files should be covered as well. I will do an additional check if there are classes not covered by notice files.
