### ISSUE TITLE
Hibernate hbm2ddl policy should be "validate" instead of "update"

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#34]
Originally reported on Google Code with ID 36

```
JWPL doesn't use hibernate to generate the database schema. It's set up during the import
of the SQL file that JWPL generates. Thus, hibernate should be able to operate in a
pure read-only mode. This includes verifying the database schema against the Hibernate
mappings, but not trying to update the DB.

hibernate.hbm2ddl.auto=validate
```

Reported by `richard.eckart` on 2011-07-17 10:54:18

**Comment by mawiesne** [comment]
In 2018, this kind of unexpected behaviour is still around. Last reported by @tgalery via a comment in #160.

**Comment by mawiesne** [comment]
I'm closing this issue as "resolved" as in the most recent version of `WikiHibernateUtil` we read:

`p.setProperty("hibernate.hbm2ddl.auto","validate");`

which is what the issue intends to address.
